runtime: php55

handlers:
# Serve php scripts.
- url: /mutant/
  script: mutant/index.php
- url: /
  script: index.php
- url: /stats/
  script: stats/index.php
- url: /insert/.*
  script: insert/index.php